# Generated by Django 5.2.7 on 2026-01-02 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researcharticle',
            name='summary',
        ),
        migrations.AddField(
            model_name='researcharticle',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='researcharticle',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
